/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type DepartmentsKey =
    | "clinic-management"
    | "childrens-ophthalmologists"
    | "consultation-and-diagnostic-ophthalmologists"
    | "doctors-anesthesiologists"
    | "ophthalmic-surgeons";

export type ServicesKey =
    | "lazerine-akiu-korekcija"
    | "akiu-patikrinimas"
    | "kataraktos-operacija"
    | "vaiku-akiu-patikra"
    | "keratokonuso-gydymas"
    | "glaukomos-gydymas"
    | "skaidraus-lesio-operacija"
    | "pratimai-akims"
    | "kontaktiniai-l\u0119\u0161iai"
    | "regos-profilaktika"
    | "\u012Fdomyb\u0117s-apie-akis-ir-reg\u0105"
    | "akiniai"
    | "aki\u0173-ligos-ir-traumos"
    | "informacija"
    | "rega-ir-am\u017Eius"
    | "rega-ir-mityba"
    | "regos-gydymas";

export type PortableTextAll = Array<
    | {
          children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
              href?: string;
              openInNewTab?: boolean;
              _type: "link";
              _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
      }
    | {
          asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          maxH?: string;
          _type: "image";
          _key: string;
      }
    | {
          gap?: boolean;
          headers?: Array<string>;
          rows?: Array<{
              cells?: Array<string>;
              _type: "row";
              _key: string;
          }>;
          _type: "table";
          _key: string;
      }
>;

export type PortableText = Array<{
    children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
}>;

export type PriceBlock = {
    _type: "priceBlock";
    servicesKey?: ServicesKey;
    icon?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    list?: Array<
        {
            _key: string;
        } & PriceItem
    >;
    linkToPage?: string;
    servicesName?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    servicesDescription?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
};

export type DiscountData = {
    _type: "discountData";
    servicesKey?: ServicesKey;
    title?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    discountShortData?: DiscountShortData;
    discountFullData?: DiscountFullData;
};

export type DiscountFullData = {
    _type: "discountFullData";
    fractionUp?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    fractionDown?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    textLeft?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    textRight?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
    discountFullText?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextAllValue
    >;
};

export type DiscountShortData = {
    _type: "discountShortData";
    premium?: boolean;
    premiumText?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    shortText?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    period?: string;
    icon?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    bgimage?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    cost?: number;
    learnMore?: boolean;
};

export type PriceItem = {
    _type: "priceItem";
    serviceName?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    price?: number;
    lowerPriceLimit?: boolean;
    discountPrice?: number;
    lowerDiscountLimit?: boolean;
    specialPrice?: boolean;
    new?: boolean;
    serviceDescription?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
};

export type OrderDoctors = {
    _id: string;
    _type: "orderDoctors";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    doctors?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "doctor";
    }>;
};

export type Blog = {
    _id: string;
    _type: "blog";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    slug?: Slug;
    service?: ServicesKey;
    publication?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    shortText?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    content?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextAllValue
    >;
};

export type Doctor = {
    _id: string;
    _type: "doctor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    slug?: Slug;
    departments?: Array<
        {
            _key: string;
        } & DepartmentsKey
    >;
    services?: Array<
        {
            _key: string;
        } & ServicesKey
    >;
    position?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
    photo?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    experience?: string;
    specialization?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
    education?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
    activity?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
    training?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
    conferences?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
    about?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextAllValue
    >;
};

export type OffersPage = {
    _id: string;
    _type: "offersPage";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    discountsData?: Array<
        {
            _key: string;
        } & DiscountData
    >;
};

export type PricesPage = {
    _id: string;
    _type: "pricesPage";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    priceBlocks?: Array<
        {
            _key: string;
        } & PriceBlock
    >;
};

export type InternationalizedArrayPortableTextAllValue = {
    _type: "internationalizedArrayPortableTextAllValue";
    value?: PortableTextAll;
};

export type InternationalizedArrayPortableTextValue = {
    _type: "internationalizedArrayPortableTextValue";
    value?: PortableText;
};

export type InternationalizedArrayTextValue = {
    _type: "internationalizedArrayTextValue";
    value?: string;
};

export type InternationalizedArrayStringValue = {
    _type: "internationalizedArrayStringValue";
    value?: string;
};

export type InternationalizedArrayPortableTextAll = Array<
    {
        _key: string;
    } & InternationalizedArrayPortableTextAllValue
>;

export type InternationalizedArrayPortableText = Array<
    {
        _key: string;
    } & InternationalizedArrayPortableTextValue
>;

export type InternationalizedArrayText = Array<
    {
        _key: string;
    } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
    {
        _key: string;
    } & InternationalizedArrayStringValue
>;

export type SanityImagePaletteSwatch = {
    _type: "sanity.imagePaletteSwatch";
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: "sanity.imagePalette";
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: "sanity.imageDimensions";
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type SanityImageHotspot = {
    _type: "sanity.imageHotspot";
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type SanityImageCrop = {
    _type: "sanity.imageCrop";
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityFileAsset = {
    _id: string;
    _type: "sanity.fileAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
    _type: "sanity.imageMetadata";
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type Geopoint = {
    _type: "geopoint";
    lat?: number;
    lng?: number;
    alt?: number;
};

export type Slug = {
    _type: "slug";
    current?: string;
    source?: string;
};

export type SanityAssetSourceData = {
    _type: "sanity.assetSourceData";
    name?: string;
    id?: string;
    url?: string;
};

export type AllSanitySchemaTypes =
    | DepartmentsKey
    | ServicesKey
    | PortableTextAll
    | PortableText
    | PriceBlock
    | DiscountData
    | DiscountFullData
    | DiscountShortData
    | PriceItem
    | OrderDoctors
    | Blog
    | Doctor
    | OffersPage
    | PricesPage
    | InternationalizedArrayPortableTextAllValue
    | InternationalizedArrayPortableTextValue
    | InternationalizedArrayTextValue
    | InternationalizedArrayStringValue
    | InternationalizedArrayPortableTextAll
    | InternationalizedArrayPortableText
    | InternationalizedArrayText
    | InternationalizedArrayString
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageHotspot
    | SanityImageCrop
    | SanityFileAsset
    | SanityImageAsset
    | SanityImageMetadata
    | Geopoint
    | Slug
    | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: pricesPageQuery
// Query: *[_type == "pricesPage" && !(_id in path("drafts.**"))][0].priceBlocks[] {servicesKey, "servicesName": servicesName[_key == $language][0].value, linkToPage,    "list":list[]{new, price, lowerPriceLimit, discountPrice, lowerDiscountLimit, specialPrice,                 "serviceName": serviceName[_key == $language][0].value,                 "serviceDescription":serviceDescription[_key == $language][0].value},    "servicesDescription":servicesDescription[_key == $language][0].value }
export type PricesPageQueryResult = Array<{
    servicesKey: ServicesKey | null;
    servicesName: string | null;
    linkToPage: string | null;
    list: Array<{
        new: boolean | null;
        price: number | null;
        lowerPriceLimit: boolean | null;
        discountPrice: number | null;
        lowerDiscountLimit: boolean | null;
        specialPrice: boolean | null;
        serviceName: string | null;
        serviceDescription: PortableText | null;
    }> | null;
    servicesDescription: PortableText | null;
}> | null;
// Variable: pricesShortQuery
// Query: *[_type == "pricesPage" && !(_id in path("drafts.**"))][0].priceBlocks[] {servicesKey,    "list":list[]{price, lowerPriceLimit, discountPrice, lowerDiscountLimit}}
export type PricesShortQueryResult = Array<{
    servicesKey: ServicesKey | null;
    list: Array<{
        price: number | null;
        lowerPriceLimit: boolean | null;
        discountPrice: number | null;
        lowerDiscountLimit: boolean | null;
    }> | null;
}> | null;
// Variable: offersPageQuery
// Query: *[_type == "offersPage" && !(_id in path("drafts.**"))][0].discountsData[]{servicesKey, "title":title[_key == $language][0].value, discountFullData{"textRight":textRight[_key == $language][0].value, "textLeft":textLeft[_key == $language][0].value,                   "fractionDown":fractionDown[_key == $language][0].value, "fractionUp":fractionUp[_key == $language][0].value,                   "discountFullText":discountFullText[_key == $language][0].value},  discountShortData{"bgimage":bgimage.asset->url, "icon":icon.asset->url, premium, "premiumText":premiumText[_key == $language][0].value, "shortText":shortText[_key == $language][0].value, period, cost, learnMore },}
export type OffersPageQueryResult = Array<{
    servicesKey: ServicesKey | null;
    title: string | null;
    discountFullData: {
        textRight: PortableText | null;
        textLeft: string | null;
        fractionDown: string | null;
        fractionUp: string | null;
        discountFullText: PortableTextAll | null;
    } | null;
    discountShortData: {
        bgimage: string | null;
        icon: string | null;
        premium: boolean | null;
        premiumText: string | null;
        shortText: string | null;
        period: string | null;
        cost: number | null;
        learnMore: boolean | null;
    } | null;
}> | null;
// Variable: offersShortQuery
// Query: *[_type == "offersPage" && !(_id in path("drafts.**"))][0].discountsData[]{servicesKey, "title":title[_key == $language][0].value, discountShortData{"bgimage":bgimage.asset->url, "icon":icon.asset->url, premium, "premiumText":premiumText[_key == $language][0].value, "shortText":shortText[_key == $language][0].value, period, cost, learnMore },}
export type OffersShortQueryResult = Array<{
    servicesKey: ServicesKey | null;
    title: string | null;
    discountShortData: {
        bgimage: string | null;
        icon: string | null;
        premium: boolean | null;
        premiumText: string | null;
        shortText: string | null;
        period: string | null;
        cost: number | null;
        learnMore: boolean | null;
    } | null;
}> | null;
// Variable: doctorsListQuery
// Query: *[_type == "doctor" && !(_id in path("drafts.**"))]{"name":name[_key == $language][0].value, "slug":slug.current, departments, services,   "position":position[_key == $language][0].value, "photo":photo,   experience, "specialization":specialization[_key == $language][0].value,   "education":education[_key == $language][0].value, "activity":activity[_key == $language][0].value,   "training":training[_key == $language][0].value, "conferences":conferences[_key == $language][0].value,   "about":about[_key == $language][0].value}
export type DoctorsListQueryResult = Array<{
    name: string | null;
    slug: string | null;
    departments: Array<
        {
            _key: string;
        } & DepartmentsKey
    > | null;
    services: Array<
        {
            _key: string;
        } & ServicesKey
    > | null;
    position: PortableText | null;
    photo: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    } | null;
    experience: string | null;
    specialization: PortableText | null;
    education: PortableText | null;
    activity: PortableText | null;
    training: PortableText | null;
    conferences: PortableText | null;
    about: PortableTextAll | null;
}>;
// Variable: doctorQuery
// Query: *[_type == "doctor" && slug.current == $slug][0]{"name":name[_key == $language][0].value, "slug":slug.current, departments, services,   "position":position[_key == $language][0].value, "photo":photo,   experience, "specialization":specialization[_key == $language][0].value,   "education":education[_key == $language][0].value, "activity":activity[_key == $language][0].value,   "training":training[_key == $language][0].value, "conferences":conferences[_key == $language][0].value,   "about":about[_key == $language][0].value}
export type DoctorQueryResult = {
    name: string | null;
    slug: string | null;
    departments: Array<
        {
            _key: string;
        } & DepartmentsKey
    > | null;
    services: Array<
        {
            _key: string;
        } & ServicesKey
    > | null;
    position: PortableText | null;
    photo: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    } | null;
    experience: string | null;
    specialization: PortableText | null;
    education: PortableText | null;
    activity: PortableText | null;
    training: PortableText | null;
    conferences: PortableText | null;
    about: PortableTextAll | null;
} | null;
// Variable: blogsListQuery
// Query: *[_type == "blog" && !(_id in path("drafts.**"))]{   service, "title":title[_key == $language][0].value,     "slug":slug.current, publication, "image":image.asset->url,     "shortText":shortText[_key == $language][0].value,     "content": content[_key == $language][0].value}
export type BlogsListQueryResult = Array<{
    service: ServicesKey | null;
    title: string | null;
    slug: string | null;
    publication: string | null;
    image: string | null;
    shortText: string | null;
    content: PortableTextAll | null;
}>;
// Variable: blogQuery
// Query: *[_type == "blog" && slug.current == $slug][0]{   service, "title":title[_key == $language][0].value,     publication, "slug":slug.current, "image":image.asset->url,     "shortText":shortText[_key == $language][0].value,     "content": content[_key == $language][0].value}
export type BlogQueryResult = {
    service: ServicesKey | null;
    title: string | null;
    publication: string | null;
    slug: string | null;
    image: string | null;
    shortText: string | null;
    content: PortableTextAll | null;
} | null;
// Variable: blogShortByServiceQuery
// Query: *[_type == "blog" && service == $service && slug.current != $slug]{   service, "title":title[_key == $language][0].value,     publication, "slug":slug.current, "image":image.asset->url,     "content": content[_key == $language][0].value,     "shortText":shortText[_key == $language][0].value }
export type BlogShortByServiceQueryResult = Array<{
    service: ServicesKey | null;
    title: string | null;
    publication: string | null;
    slug: string | null;
    image: string | null;
    content: PortableTextAll | null;
    shortText: string | null;
}>;
// Variable: doctorsOrderQuery
// Query: *[_type == "orderDoctors"][0].  doctors[]->{    _id,  "name":name[_key == $language][0].value, "slug":slug.current, departments, services,   "position":position[_key == $language][0].value, "photo":photo,   experience, "specialization":specialization[_key == $language][0].value,   "education":education[_key == $language][0].value, "activity":activity[_key == $language][0].value,   "training":training[_key == $language][0].value, "conferences":conferences[_key == $language][0].value,   "about":about[_key == $language][0].value  }
export type DoctorsOrderQueryResult = Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    departments: Array<
        {
            _key: string;
        } & DepartmentsKey
    > | null;
    services: Array<
        {
            _key: string;
        } & ServicesKey
    > | null;
    position: PortableText | null;
    photo: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    } | null;
    experience: string | null;
    specialization: PortableText | null;
    education: PortableText | null;
    activity: PortableText | null;
    training: PortableText | null;
    conferences: PortableText | null;
    about: PortableTextAll | null;
}> | null;
// Variable: blogMetaSlugsQuery
// Query: *[_type == "blog" && !(_id in path("drafts.**"))].slug.current
export type BlogMetaSlugsQueryResult = Array<string | null>;
// Variable: doctorMetaSlugsQuery
// Query: *[_type == "doctor" && !(_id in path("drafts.**"))].slug.current
export type DoctorMetaSlugsQueryResult = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
    interface SanityQueries {
        '\n    *[_type == "pricesPage" && !(_id in path("drafts.**"))][0].priceBlocks[]\n {servicesKey, "servicesName": servicesName[_key == $language][0].value, linkToPage, \n   "list":list[]{new, price, lowerPriceLimit, discountPrice, lowerDiscountLimit, specialPrice,\n                 "serviceName": serviceName[_key == $language][0].value,\n                 "serviceDescription":serviceDescription[_key == $language][0].value}, \n   "servicesDescription":servicesDescription[_key == $language][0].value }': PricesPageQueryResult;
        '\n    *[_type == "pricesPage" && !(_id in path("drafts.**"))][0].priceBlocks[]\n {servicesKey, \n   "list":list[]{price, lowerPriceLimit, discountPrice, lowerDiscountLimit}}': PricesShortQueryResult;
        '\n    *[_type == "offersPage" && !(_id in path("drafts.**"))][0].discountsData[]\n{servicesKey, "title":title[_key == $language][0].value,\n discountFullData{"textRight":textRight[_key == $language][0].value, "textLeft":textLeft[_key == $language][0].value, \n                  "fractionDown":fractionDown[_key == $language][0].value, "fractionUp":fractionUp[_key == $language][0].value, \n                  "discountFullText":discountFullText[_key == $language][0].value}, \n discountShortData{"bgimage":bgimage.asset->url, "icon":icon.asset->url, premium, "premiumText":premiumText[_key == $language][0].value, "shortText":shortText[_key == $language][0].value, period, cost, learnMore },}': OffersPageQueryResult;
        '\n    *[_type == "offersPage" && !(_id in path("drafts.**"))][0].discountsData[]\n{servicesKey, "title":title[_key == $language][0].value,\n discountShortData{"bgimage":bgimage.asset->url, "icon":icon.asset->url, premium, "premiumText":premiumText[_key == $language][0].value, "shortText":shortText[_key == $language][0].value, period, cost, learnMore },}': OffersShortQueryResult;
        '\n    *[_type == "doctor" && !(_id in path("drafts.**"))]\n{"name":name[_key == $language][0].value, "slug":slug.current, departments, services, \n  "position":position[_key == $language][0].value, "photo":photo, \n  experience, "specialization":specialization[_key == $language][0].value, \n  "education":education[_key == $language][0].value, "activity":activity[_key == $language][0].value, \n  "training":training[_key == $language][0].value, "conferences":conferences[_key == $language][0].value, \n  "about":about[_key == $language][0].value}': DoctorsListQueryResult;
        '\n    *[_type == "doctor" && slug.current == $slug][0]\n{"name":name[_key == $language][0].value, "slug":slug.current, departments, services, \n  "position":position[_key == $language][0].value, "photo":photo, \n  experience, "specialization":specialization[_key == $language][0].value, \n  "education":education[_key == $language][0].value, "activity":activity[_key == $language][0].value, \n  "training":training[_key == $language][0].value, "conferences":conferences[_key == $language][0].value, \n  "about":about[_key == $language][0].value}': DoctorQueryResult;
        '\n     *[_type == "blog" && !(_id in path("drafts.**"))]{\n   service, "title":title[_key == $language][0].value,\n     "slug":slug.current, publication, "image":image.asset->url,\n     "shortText":shortText[_key == $language][0].value,\n     "content": content[_key == $language][0].value}': BlogsListQueryResult;
        '\n      *[_type == "blog" && slug.current == $slug][0]{\n   service, "title":title[_key == $language][0].value,\n     publication, "slug":slug.current, "image":image.asset->url,\n     "shortText":shortText[_key == $language][0].value,\n     "content": content[_key == $language][0].value}': BlogQueryResult;
        '\n      *[_type == "blog" && service == $service && slug.current != $slug]{\n   service, "title":title[_key == $language][0].value,\n     publication, "slug":slug.current, "image":image.asset->url,\n     "content": content[_key == $language][0].value,\n     "shortText":shortText[_key == $language][0].value\n }': BlogShortByServiceQueryResult;
        '\n*[_type == "orderDoctors"][0].\n  doctors[]->{\n    _id,\n  "name":name[_key == $language][0].value, "slug":slug.current, departments, services, \n  "position":position[_key == $language][0].value, "photo":photo, \n  experience, "specialization":specialization[_key == $language][0].value, \n  "education":education[_key == $language][0].value, "activity":activity[_key == $language][0].value, \n  "training":training[_key == $language][0].value, "conferences":conferences[_key == $language][0].value, \n  "about":about[_key == $language][0].value\n  }': DoctorsOrderQueryResult;
        '\n      *[_type == "blog" && !(_id in path("drafts.**"))].slug.current\n': BlogMetaSlugsQueryResult;
        '\n      *[_type == "doctor" && !(_id in path("drafts.**"))].slug.current\n': DoctorMetaSlugsQueryResult;
    }
}
