import type { MetadataRoute } from "next";

import { sanityFetch } from "@/sanity/lib/live";
import { blogMetaSlugsQuery, doctorMetaSlugsQuery } from "@/sanity/lib/queries";
export const dynamic = "force-static";
export const revalidate = 3600;

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;
    const now = new Date("2026-01-01");

    const blogsSlugsList = await sanityFetch({
        query: blogMetaSlugsQuery,
        params: {},
        tags: ["blog"],
    });

    const blogsSlugs = blogsSlugsList.data.flatMap(item => [
        {
            url: `${baseUrl}/blog/${item}`,
            lastModified: now,
            changeFrequency: "weekly" as const,
            priority: 0.5,
        },
        {
            url: `${baseUrl}/en/blog/${item}`,
            lastModified: now,
            changeFrequency: "weekly" as const,
            priority: 0.5,
        },
        {
            url: `${baseUrl}/ru/blog/${item}`,
            lastModified: now,
            changeFrequency: "weekly" as const,
            priority: 0.5,
        },
    ]);

    const doctorsSlugsList = await sanityFetch({
        query: doctorMetaSlugsQuery,
        params: {},
        tags: ["doctor"],
    });

    const doctorsSlugs = doctorsSlugsList.data.flatMap(item => [
        {
            url: `${baseUrl}/gydytojai/${item}`,
            lastModified: now,
            changeFrequency: "monthly" as const,
            priority: 0.5,
        },
        {
            url: `${baseUrl}/en/doctors/${item}`,
            lastModified: now,
            changeFrequency: "monthly" as const,
            priority: 0.5,
        },
        {
            url: `${baseUrl}/ru/vrachi/${item}`,
            lastModified: now,
            changeFrequency: "monthly" as const,
            priority: 0.5,
        },
    ]);

    return [
        {
            url: `${baseUrl}/`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 1.0,
        },
        {
            url: `${baseUrl}/paslaugos`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/rayner-galaxy-lt`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/kainos`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/akcijos`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/gydytojai`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/apie-klinika`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/informacija-pacientams`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/atsiliepimai`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/kontaktai`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        // послуги
        {
            url: `${baseUrl}/paslaugos/lazerine-akiu-korekcija`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/paslaugos/akiu-patikrinimas`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/paslaugos/kataraktos-operacija`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/paslaugos/dry-eye-syndrome-treatment`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/paslaugos/vaiku-akiu-patikra`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/paslaugos/lazerinis-akiu-ligu-gydymas`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/paslaugos/skaidraus-lesio-operacija`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/paslaugos/glaukomos-gydymas`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/en`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/ru`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/files/licence.pdf`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/blog`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/privatumo-politika`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/en/services`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/rayner-galaxy-a-new-dimension-of-vision-is-now-available-at-our-clinic`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/rayner-galaxy-novoe-izmerenie-zreniya-uzhe-v-nashej-klinike`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/price-list`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/ceny-na-uslugi`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/offers`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/akcii`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/doctors`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/vrachi`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/our-clinic`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/o-klinike`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/patient-information`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/informatsiya-dlya-patsiyentov`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/information-for-out-of-town-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/reminders-and-instructions-for-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/instructions-before-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/preparation-for-surgery-for-strabismus`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/reminder-before-a-comprehensive-pediatric-examination`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/patient-information-before-IPL-therapy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/pamyatka-patsiyenta-pered-vitreoretynalnoyu-khirurhiyeyu`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/instructions-after-laser-vision-correction`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/pamyatka-patsiyenta-pislya-khirurhiyi-katarakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/akiu-ligos`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/akiu-ligos/glaukoma`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/akiu-ligos/presbiopija`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/akiu-ligos/toliaregyste`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/akiu-ligos/katarakta`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/akiu-ligos/akiu-ligu-simptomai`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/akiu-ligos/zvairumas`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/akiu-ligos/trumparegyste-miopija`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/akiu-ligos/astigmatizmas`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/testimonials`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/otzyvy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/contacts`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/kontakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/laser-eye-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lazernaya-korrekciya-zreniya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/paslaugos/lazerine-akiu-korekcija/iq-lasik-oxygen-3d`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/paslaugos/lazerine-akiu-korekcija/sportlife-lasik`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/eye-examination`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/diagnostika-zreniya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/cataract-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/udaleniye-katarakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/paslaugos/kataraktos-operacija/iq-5-minutes`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/paslaugos/kataraktos-operacija/iq-life-3d`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/dry-eye-syndrome`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lechenie-sindroma-suhogo-glaza`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/pediatric-eye-examination`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/detskoye-otdeleniye`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/laser-treatment-of-eye-diseases`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lazernoye-lecheniye-zabolevaniy-glaza`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/refractive-lens-exchange`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/khirurgiia-prozrachnogo-khrustalika`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/vitreoretinal-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/vitreoretinalnaya-khirurgiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/intravitreal-injections`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/intravitrealnyye-inyektsii`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/glaukomos-gydymas`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/glaukomos-gydymas`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/strabismus-treatment`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lecheniye-kosoglaziya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/eyelid-and-conjunctival-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/khirurgiya-vek-i-konyunktivy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/anesthesia-benefit`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/anesteziologicheskoye-posobiye`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/xenon-therapy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/blog`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/privacy-policy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/blog`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/privacy-policy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/information-for-out-of-town-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/reminders-and-instructions-for-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/instructions-before-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/instructions-after-laser-vision-correction`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/glaucoma`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/presbyopia`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/farsightedness`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/cataract`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/symptoms-of-eye-disease`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/strabismus`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/nearsightedness-myopia`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/astigmatism`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/information-for-out-of-town-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/dovanu-kupono`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/dovanu-kupono`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/dovanu-kupono`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/reminders-and-instructions-for-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/instructions-before-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/instructions-after-laser-vision-correction`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/pamyatki-paczienta-posle-hirurgii-katarakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-zabolevaniya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-zabolevaniya/glaukoma`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-zabolevaniya/pryesbiopiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-zabolevaniya/dalnozorkost`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-zabolevaniya/katarakta`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-zabolevaniya/simptomy-zabolevaniya-glaz`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-zabolevaniya/kosoglazie`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-zabolevaniya/blizorukost-miopiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-zabolevaniya/astigmatizm`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/services/laser-eye-surgery/iq-lasik-oxygen-3d`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/services/laser-eye-surgery/sportlife-lasik`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/uslugi/lazernaya-korrekciya-zreniya/iq-lasik-oxygen-3d`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/uslugi/lazernaya-korrekciya-zreniya/sportlife-lasik`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/services/cataract-surgery/iq-5-minutes`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/services/cataract-surgery/iq-life-3d-live-vision`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/uslugi/udaleniye-katarakty/iq-5-minutes`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/uslugi/udaleniye-katarakty/iq-life-3d-zhivoye-zreniye`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        ...blogsSlugs,
        ...doctorsSlugs,
    ];
}
